all:
	g++ -o main main.cpp -I /usr/include/eigen3/ -I /opt/gurobi810/linux64/include/ -L/opt/gurobi810/linux64/lib -lgurobi_c++ -lgurobi81
parallel:
	g++ -o main main.cpp -I /usr/include/eigen3/ -I /opt/gurobi810/linux64/include/ -L/opt/gurobi810/linux64/lib -lgurobi_c++ -lgurobi81 -fopenmp
